package core

import (
	"fmt"
	"regexp"
	"strings"
	"time"

	"trellis/internal/model"
	"trellis/internal/store"
)

var featureSubjectRe = regexp.MustCompile(`^Merge feature/(US-\d+): (.+) \(trellis finish\)$`)

// parseFeatureSubjects extracts "US-n — title" lines from git merge subjects
// written by finish; anything else is ignored.
func parseFeatureSubjects(subjects []string) []string {
	var out []string
	for _, s := range subjects {
		if m := featureSubjectRe.FindStringSubmatch(strings.TrimSpace(s)); m != nil {
			out = append(out, m[1]+" — "+m[2])
		}
	}
	return out
}

// featuresMarkdown renders FEATURES.md: done feature headings plus the
// glossary. Lives only on the release branch.
func featuresMarkdown(name, description string, stories []model.Node, terms []store.TermDef) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", name)
	if description != "" {
		fmt.Fprintf(&b, "> %s\n\n", description)
	}
	b.WriteString("## Features\n\n")
	if len(stories) == 0 {
		b.WriteString("_none yet_\n")
	}
	for _, s := range stories {
		fmt.Fprintf(&b, "- **%s** — %s\n", s.ID, s.Title)
	}
	if len(terms) > 0 {
		b.WriteString("\n## Glossary\n\n")
		for _, td := range terms {
			fmt.Fprintf(&b, "- **%s** — %s\n", td.Term, td.Definition)
		}
	}
	b.WriteString("\n_Generated by trellis release; this file lives only on the release branch._\n")
	return b.String()
}

// Release merges the base branch into the release branch with a feature-list
// merge message and regenerates FEATURES.md there. A human act: exposed only
// on the CLI, never via MCP.
func (e *Engine) Release() (string, error) {
	g, err := e.git()
	if err != nil {
		return "", err
	}
	base, rel := e.Project.BaseBranch, e.Project.ReleaseBranch
	if rel == "" {
		rel = "main"
	}
	if rel == base {
		return "", fmt.Errorf("release blocked: release branch equals base branch %q — configure a different one (trellis config --release)", base)
	}
	if clean, err := g.IsClean(); err != nil {
		return "", err
	} else if !clean {
		return "", fmt.Errorf("release blocked: main worktree not clean, commit or stash first")
	}
	o, err := e.Overview()
	if err != nil {
		return "", err
	}
	if len(o.StaleNodes) > 0 {
		return "", fmt.Errorf("release blocked: a release snapshots honest context, but these specs are stale:\n- %s",
			strings.Join(o.StaleNodes, "\n- "))
	}

	// Delta: feature merges on base that the release branch does not have yet.
	firstRelease := !g.BranchExists(rel)
	logRange := base
	if !firstRelease {
		logRange = rel + ".." + base
	}
	subjects, err := g.Run("log", logRange, "--merges", "--pretty=%s")
	if err != nil {
		return "", err
	}
	features := parseFeatureSubjects(strings.Split(subjects, "\n"))
	if len(features) == 0 {
		return "", fmt.Errorf("release blocked: nothing to release — no new feature merges on %s since the last release", base)
	}

	if firstRelease {
		if _, err := g.Run("branch", rel, base); err != nil {
			return "", err
		}
	}
	if _, err := g.Run("checkout", rel); err != nil {
		return "", err
	}
	restore := func() { _, _ = g.Run("checkout", base) }

	msg := fmt.Sprintf("Release %s: %d feature(s)\n", time.Now().Format("2006-01-02"), len(features))
	for _, f := range features {
		msg += "\n- " + f
	}
	if !firstRelease {
		if _, err := g.Run("merge", "--no-ff", "-m", msg, base); err != nil {
			_, _ = g.Run("merge", "--abort")
			restore()
			return "", fmt.Errorf("release blocked: merge into %s failed and was aborted: %w", rel, err)
		}
	}

	// Regenerate the manifest on the release branch only.
	stories, err := e.st.ListNodesByKind(e.pid(), model.KindStory)
	if err != nil {
		restore()
		return "", err
	}
	var done []model.Node
	for _, s := range stories {
		if s.Status == model.StatusDone {
			done = append(done, s)
		}
	}
	terms, err := e.st.ListTerms(e.pid())
	if err != nil {
		restore()
		return "", err
	}
	if err := g.WriteFile("FEATURES.md", featuresMarkdown(e.Project.Name, e.Project.Description, done, terms)); err != nil {
		restore()
		return "", err
	}
	// Every release doubles as a backup: the full spec database rides along
	// as human-readable YAML.
	export, err := e.ExportYAML()
	if err != nil {
		restore()
		return "", err
	}
	if err := g.WriteFile("trellis-specs.yaml", export); err != nil {
		restore()
		return "", err
	}
	if _, err := g.Run("add", "FEATURES.md", "trellis-specs.yaml"); err != nil {
		restore()
		return "", err
	}
	commitMsg := msg
	if !firstRelease {
		commitMsg = "Update release manifests"
	}
	if _, err := g.Run("commit", "-m", commitMsg); err != nil {
		// Nothing changed in the manifest: fine after a pure merge.
		if !strings.Contains(err.Error(), "nothing to commit") {
			restore()
			return "", err
		}
	}
	restore()
	e.st.AppendEvent(e.pid(), "release", "", fmt.Sprintf("%d feature(s) -> %s", len(features), rel))
	return fmt.Sprintf("released %d feature(s) to %s:\n- %s", len(features), rel, strings.Join(features, "\n- ")), nil
}
